import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Metadata } from "next";
import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core/lib";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";
import { inter } from "@/shared/fonts";

export const metadata: Metadata = {
  title: "TECH-FRONTEND",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children, params: { locale } }) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  return (
    <html lang={locale} {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale}>
          <MantineProvider>
            <Header locale={locale} />
            <main>{children}</main>
            <Footer />
          </MantineProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
