name: Build and Deploy Directly on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            echo "Starting SSH connection..."
            ssh -v -i ~/.ssh/github_actions ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "
            cd /apps/frontend
            git pull origin main
            cd ..
            docker-compose build nextjs
            docker-compose up -d --no-deps nextjs
            docker system prune -f
