name: Build and Deploy Directly on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ../apps/frontend
            
            GIT_SSH_COMMAND="ssh -i ~/.ssh/github_actions -o StrictHostKeyChecking=no" git pull origin main

            # Возвращаемся на уровень выше для доступа к `docker-compose.yml`
            cd ..

            # Собираем образ, но не запускаем его сразу
            docker-compose build nextjs

            # Запускаем новый контейнер frontend только после успешной сборки
            docker-compose up -d --no-deps nextjs

            # Очищаем неиспользуемые образы, чтобы освободить место
            docker system prune -f
